import type { DashboardState } from '@/types';

export function makeDashboardState(overrides: Partial<DashboardState> = {}): DashboardState {
  const state: DashboardState = {
    now: Date.now(),
    cpu: {
      model: 'AMD Ryzen 9 9950X3D',
      cores: 16,
      threads: 32,
      usage: 42,
      target: 70,
      tempC: 55,
      tempTarget: 80,
      history: [20, 35, 42],
      tempHistory: [45, 50, 55],
      coreList: [{ id: 0, pct: 42, target: 70 }],
    },
    ram: {
      totalGB: 64,
      usedGB: 24,
      target: 80,
      cachedGB: 4,
      history: [20, 30, 38],
    },
    gpu: {
      model: 'RTX 5070 Ti',
      usage: 30,
      target: 70,
      memUsedGB: 6,
      memTotalGB: 16,
      tempC: 48,
      powerW: 120,
      powerMaxW: 300,
      fanPct: 40,
      gpuClockMHz: 2200,
      memClockMHz: 1400,
      history: [10, 25, 30],
    },
    gpus: [],
    gpuUnavailable: [],
    fans: [{ name: 'Case fan', rpm: 1200, target: 1500, max: 2000 }],
    storage: {
      pools: [
        { name: 'tank', type: 'RAID 5', totalTB: 8, usedTB: 2, status: 'online', scrub: 'ok' },
      ],
      disks: [{ name: 'Disk 1', model: 'IronWolf', tempC: 34, smart: 'ok', ageHours: 100 }],
    },
    docker: {
      running: 3,
      stopped: 0,
      total: 3,
      updates: 0,
      hosts: [
        {
          id: '1',
          name: 'container-host',
          addr: '198.51.100.10',
          os: 'Debian',
          engine: '27.0',
          cpu: 10,
          ram: 20,
          status: 'online',
        },
      ],
      containers: [],
    },
    proxmox: {
      nodes: [
        {
          name: 'compute-node',
          cpu: 25,
          maxcpu: 16,
          ram: 50,
          ramUsedGB: 32,
          ramTotalGB: 64,
          disk: 25,
          diskUsedTB: 2,
          diskTotalTB: 8,
          uptime: '1d',
          uptimeSec: 86400,
          status: 'online',
          level: null,
        },
      ],
      cluster: {
        nodesOnline: 1,
        nodesTotal: 1,
        cpuUsed: 4,
        cpuTotal: 16,
        cpuPct: 25,
        memUsedGB: 32,
        memTotalGB: 64,
        memPct: 50,
        storageUsedTB: 2,
        storageTotalTB: 8,
        storagePct: 25,
        guestsRunning: 1,
        guestsTotal: 1,
      },
      node: {
        name: 'compute-node',
        ip: '198.51.100.10',
        cpu: 25,
        ram: 50,
        ramUsedGB: 32,
        ramTotalGB: 64,
        ramAllocatedGB: 12,
        cpuModel: 'Ryzen',
        cpuCores: 16,
        cpuThreads: 32,
        storageUsedTB: 2,
        storageTotalTB: 8,
        storagePct: 25,
        uptime: '1d',
        version: '9.1.6',
      },
      vms: [
        {
          id: 105,
          name: 'ai-lab',
          type: 'LXC',
          state: 'running',
          cpu: 10,
          ram: 50,
          disk: 64,
          node: 'compute-node',
          ip: null,
        },
      ],
      disks: [],
      storages: [],
      coresAllocated: 4,
      coresTotal: 16,
    },
    unifi: {
      gateway: {
        model: 'UCG-X',
        cpu: 12,
        ram: 34,
        tempC: 42,
        uptime: '1d',
        fwVersion: '9.0.1',
      },
      switches: [],
      aps: [],
      clients: 2,
      clientBreakdown: { wired: 1, wireless: 1, vpn: 0 },
      topTalkers: [
        {
          name: 'Example Workstation',
          ip: '198.51.100.50',
          type: 'WIRED',
          access: 'DEFAULT',
          connectedAt: '',
          rxMB: 0,
          txMB: 0,
        },
      ],
      wan: { down: 150, up: 50, downMax: 1000, upMax: 1000, public: '198.51.100.20' },
      networks: [],
      ssids: [],
      firewall: {
        zones: 1,
        policies: 2,
        policiesEnabled: 1,
        zoneList: [{ id: 'zone-1', name: 'Internal', networkCount: 2 }],
        policyList: [
          {
            id: 'pol-1',
            name: 'Allow Internal to Internal',
            enabled: true,
            action: 'ALLOW',
            sourceZone: 'Internal',
            destinationZone: 'Internal',
            index: 0,
            predefined: true,
          },
          {
            id: 'pol-2',
            name: 'Block Guest to Internal',
            enabled: false,
            action: 'BLOCK',
            sourceZone: 'Guest',
            destinationZone: 'Internal',
            index: 1,
            predefined: false,
          },
        ],
      },
      vpnServers: [],
      dnsRecords: [],
      appVersion: '9.3.0',
    },
    unas: {
      name: 'Example NAS',
      model: 'UNAS 4',
      tempC: 34,
      fanProfile: 'balanced',
      pools: [],
      disks: [],
    },
    network: {
      downHistory: [100, 150],
      upHistory: [20, 50],
      latencyMs: 10,
      latencyHistory: [9, 10],
      speedtest: { down: 900, up: 900, ping: 5, when: 'now' },
      uptime30d: 99.9,
      publicIp: '198.51.100.20',
      dns: [],
    },
    backups: [{ name: 'nightly', when: 'today', status: 'ok', sizeGB: 100 }],
    ups: {
      model: 'APC',
      loadW: 100,
      loadPct: 20,
      batteryPct: 95,
      runtimeMin: 30,
      status: 'online',
    },
    events: [{ ts: 'now', kind: 'info', title: 'Boot', body: 'Dashboard loaded' }],
    alerts: [],
    sensors: {
      cpuTempC: 55,
      systemTempC: 36,
      systemTempLabel: 'Motherboard',
      cores: [],
      disks: [],
      memory: [],
      network: [],
      fans: [],
      other: [],
    },
    sensorNodes: [],
    sensorsUnavailable: [],
    amt: { devices: [], total: 0, online: 0, offline: 0, unreachable: 0 },
  };

  return { ...state, ...overrides };
}
